server:
  port: 7777
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sg_blog
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.domain.entity

oss:
  accessKey: vyDtbZMi7HY9VIxMILh-wuj16wSYJ_eW4qpo6vMo
  secretKey: 2CpvvwB5a86wlQATEcPQcAyapKulYpjDm1pQNflL
  bucket: sino-blog